[project]
name = "ai-proctor-vision-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "mediapipe==0.10.11",
    "numpy<2.0",
    "opencv-python<4.10",
    "ultralytics>=8.4.7",
]
