[project]
name = "ai-proctor-vision-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mediapipe>=0.10.32",
    "numpy>=2.4.1",
    "opencv-python>=4.13.0.90",
    "ultralytics>=8.4.7",
]
